customhost = "database-assg.c7fwwm5rtnub.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bestie123"
customdb = "database_assg"
custombucket = "lowzhiyi-bucket"
customregion = "us-east-1"
